### ISSUE TITLE
Example Data

### ISSUE THREAD

**Issue by StefanBaar** [neXyon/pynephoscope#1]
Thank you for the great script. I am currently looking through it and I am wondering if it would be possible to upload a data example (image, mask, sky catalogue, etc.)?

**Comment by neXyon** [comment]
Hi,

the star catalog I used is the Yale Bright Star Catalog and can be downloaded here: http://tdc-www.harvard.edu/catalogs/bsc5.html

As for the images I unfortunately can't  upload examples as I don't have the copyright for the images. If you want to use this code, you should have images anyway. I could share the mask, but that is pointless without the images. The mask is easy to create though: just have a png image in the same size as the images with everything white and parts that you want to mask in black.

Cheers
